### ISSUE TITLE
Disable button 

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsIncidentPortal#24] opened 2020-09-24 18:52 UTC
On page 8: When form is blanc "versturen" button should be disabled /  gray.
Like the other pages.

![image](https://user-images.githubusercontent.com/46600362/94186872-80ac7200-fea7-11ea-870d-2ef0aa565178.png)

**Comment by yorickdewid** [comment] 2020-09-24 19:11
Its not a bug, its a feature

**Comment by pnobbe** [comment] 2020-09-25 12:57
Personal information is not _actually_ required.

**Comment by yorickdewid** [comment] 2020-09-25 13:46
However, we now know that at least email is required

**Comment by pnobbe** [comment] 2020-10-01 09:20
Fixed in #28

**Closed as completed by pnobbe** 2020-10-01 09:20 UTC
Labels: enhancement, invalid
